version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gtt
      - PORT=3000
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"